# Generated by Django 6.0.6 on 2026-07-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
