# Generated by Django 6.0.6 on 2026-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_youtube_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stream_url',
            field=models.URLField(blank=True),
        ),
    ]
